### ISSUE TITLE
Do you know Ansible

### ISSUE THREAD

**Issue by MLauper** [swisscom/dopv#1]
Hey everybody

I looked at this project and was wondering if you ever heard of Ansible:
https://www.ansible.com/

This is a very similar project, but seems to be a little bit more widespread. 

How do you differentiate from Ansible?

Cheers.

**Comment by ZeroPointEnergy** [comment]
Hello
Ansible is a full fledged configuration management tool, while DOP is supposed to only orchestrate the deployment parts, the pieces currently missing from the Puppet Ecosystem.
A DOP plan describes the nodes their roles and hiera data and the steps until puppet takes over. We also provide an API (DOPc) to further automate the whole deployment process for adding and managing deployment plans.

**Comment by MLauper** [comment]
I see. 

Thank you for the clarification.
