### ISSUE TITLE
Add API and usage documentation

### ISSUE THREAD

**Issue by sspreitzer** [swisscom/dopv#2]
Hi

This project is missing proper documentation.
Specifically on the programming interface and most notable for the end user.

Maybe to take a look at:
* http://yardoc.org/
* https://github.com/tombenner/jdoc

Kind regards
Sascha

**Comment by schefDev** [comment]
Hi Sascha

Sorry for the late reply.
We tried to describe all components of DOP in a common documentation, see here:
[https://swisscom.github.io/docs-dop](https://swisscom.github.io/docs-dop)

Thank you for your contribution
Christian
